/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-10-27 04:18:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>HTML5 Form - New HTML5 Elements</title>\r\n");
      out.write("\t\t<link href=\"../../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../../js/jquery.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$(\"#login\").click(function() {\r\n");
      out.write("\t\t\t\t\tdocument.forms[0].action = \"/mobilizecarsweb/app/login/validate\";\r\n");
      out.write("\t\t\t\t\t$(\"#my-form\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#register\").click(function() {\t\t\r\n");
      out.write("\t\t\t\t\tdocument.forms[0].action = \"/mobilizecarsweb/app/login/register\";\r\n");
      out.write("\t\t\t\t\t$(\"#my-form\").submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//end doc ready\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\t<!-- <div id=\"header\" style=\"height:100px; width:1500px;  background-color:#ffcc99;\" > </div >-->\r\n");
      out.write("\t\t<div id=\"container\" style=\"height:130px; width:1200px; margin-top:-20px; background-color:#ffcc99; float:left\">\r\n");
      out.write("\t\t\t<div class=\"divRow1\">\r\n");
      out.write("\t\t\t\t<div class=\"divCell\" style=\"width:600px; float:left\">\r\n");
      out.write("\t\t\t\t\t<img id=\"logo\" src=\"../../Images/logo_car.jpg\" alt=\"Logo\" height=\"120\" width=\"250\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divCell\" style=\"width:600px;  float:left\">\r\n");
      out.write("\t\t\t\t\t<h1 align=\"right\">Buy On Mobile Inc.</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>    \r\n");
      out.write("\t\t<div name=\"dummy\"  id=\"dummy\" style=\"height:80px;  width:1200px;  float:left; background-color:#EBEBEB\"></div>\r\n");
      out.write("       <div name=\"mainContentBody\"  id=\"mainContentBody\" style=\"height:750px;  width:1200px;  float:left; background-color:#EBEBEB\">\r\n");
      out.write("       <!--<div name=\"mainContentBody\"  id=\"mainContentBody\" style=\"height:750px;  width:1200px;  float:left; background-color:#EBEBEB\"></div>-->\r\n");
      out.write("\t\t<form method=\"post\" action=\"/mobilizecarsweb/app/login/validate\" id=\"my-form\">\r\n");
      out.write("        <fieldset >\r\n");
      out.write("        <legend>Login</legend>\r\n");
      out.write("        <div>\r\n");
      out.write("        <font color='red' >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginForm.errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("  </font>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label for=\"userId\">User ID:</label>\r\n");
      out.write("          <input type=\"text\" name=\"userId\" id=\"userId\" value=\"\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          <label for=\"password\">Password:</label>\r\n");
      out.write("          <input type=\"password\" name=\"password\" id=\"password\" value=\"\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"divTable\">\r\n");
      out.write("          <div class=\"divRow\">\r\n");
      out.write("            <div class=\"divCell\" align=\"right\">\r\n");
      out.write("              <input type=\"submit\" name=\"login\" id=\"login\" value=\"Login\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"divCell\">\r\n");
      out.write("              <input type=\"button\" name=\"register\" id=\"register\" value=\"Register\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
