/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-10-27 04:18:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_005f2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=utf-8 />\r\n");
      out.write("\t\t<title>Dropdown Menu With JQuery</title>\r\n");
      out.write("\t\t<link href=\"../../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../../js/jquery.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t$('.dropdown').mouseenter(function() {\r\n");
      out.write("\t\t\t\t\t$('.sublinks').stop(false, true).hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar submenu = $(this).parent().next();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsubmenu.css({\r\n");
      out.write("\t\t\t\t\t\tposition : 'absolute',\r\n");
      out.write("\t\t\t\t\t\ttop : $(this).offset().top + $(this).height() + 'px',\r\n");
      out.write("\t\t\t\t\t\tleft : $(this).offset().left + 'px',\r\n");
      out.write("\t\t\t\t\t\tzIndex : 1000\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsubmenu.stop().slideDown(300);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsubmenu.mouseleave(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).slideUp(300);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/*function addContent(contentPage){\r\n");
      out.write("\t\t\t\t//$(\"#mainContentBody\").load(contentPage);\r\n");
      out.write("\t\t\t\t//$(\"#mainContentBody\").load(\"/mobilizecarsweb/app/userDetails\");\r\n");
      out.write("\t\t\t\talert(\"111contentPage:\"+contentPage);\r\n");
      out.write("  \t\t\t \t$(\"#mainContentBody\").load(\"/mobilizecarsweb/app/\"+contentPage);\r\n");
      out.write("\t\t\t\t//$(\"#mainContentBody\").src = \"/mobilizecarsweb/app/\"+contentPage;\r\n");
      out.write("\t\t\t\t//$(\"#main-form\").submit();\r\n");
      out.write("  \t\t\t \tdocument.forms[0].action = \"/mobilizecarsweb/app/userDetails\";\r\n");
      out.write("  \t\t\t \talert($(\"#main-form\").action);\r\n");
      out.write("\t\t\t\t$(\"#main-form\").submit();\r\n");
      out.write("\t\t\t\t        $.ajax({\r\n");
      out.write("\t        \t\t\t\ttype: \"GET\",\r\n");
      out.write("\t       \t\t\t\t\t url: \"/mobilizecarsweb/app/userDetails\",\r\n");
      out.write("\t        \t\t\t\tdata: \"\",\r\n");
      out.write("\t        \t\t\t\tsuccess: function(response){\r\n");
      out.write("\t       \t\t\t\t\t\t // we have the response\r\n");
      out.write("\t       \t\t\t\t\t\t$(\"#mainContentBody\").load(response);\r\n");
      out.write("\t       \t\t\t\t    },\r\n");
      out.write("\t       \t\t\t \t\terror: function(e){\r\n");
      out.write("\t       \t\t\t\t alert('Error: ' + e);\r\n");
      out.write("\t        \t\t\t}\r\n");
      out.write("\t        \t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}*/\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\t/* CSS For Dropdown Menu Start */\r\n");
      out.write("\t\t\tul {\r\n");
      out.write("\t\t\t\tlist-style: none;\r\n");
      out.write("\t\t\t\tpadding: 0px;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tmargin: -4px 0px 0px 0px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li {\r\n");
      out.write("\t\t\t\tdisplay: inline;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a {\r\n");
      out.write("\t\t\t\tcolor: #ffffff;\r\n");
      out.write("\t\t\t\tbackground: #990E00;\r\n");
      out.write("\t\t\t\tmargin-right: 0px;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\tfont-size: 12px;\r\n");
      out.write("\t\t\t\tfont-family: verdana;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 150px;\r\n");
      out.write("\t\t\t\theight: 25px;\r\n");
      out.write("\t\t\t\tline-height: 25px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t-webkit-border-radius: 5px;\r\n");
      out.write("\t\t\t\t-moz-border-radius: 50px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #560E00;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li a:hover {\r\n");
      out.write("\t\t\t\tcolor: #cccccc;\r\n");
      out.write("\t\t\t\tbackground: #560E00;\r\n");
      out.write("\t\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 150px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\t-webkit-border-radius: 5px;\r\n");
      out.write("\t\t\t\t-moz-border-radius: 5px;\r\n");
      out.write("\t\t\t\tborder: 1px solid #000000;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li.sublinks a {\r\n");
      out.write("\t\t\t\tcolor: #000000;\r\n");
      out.write("\t\t\t\tbackground:#999999;\r\n");
      out.write("\t\t\t\tborder-bottom: 1px solid #cccccc;\r\n");
      out.write("\t\t\t\tfont-weight: normal;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 120px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tmargin-top: 2px;\r\n");
      out.write("\t\t\t\t/*float: left; to make vertical list*/\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li.sublinks a:hover {\r\n");
      out.write("\t\t\t\tcolor: #000000;\r\n");
      out.write("\t\t\t\tbackground: #FFEFC6;\r\n");
      out.write("\t\t\t\tfont-weight: normal;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 120px;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tul li.sublinks {\r\n");
      out.write("\t\t\t\tdisplay: none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/* CSS For Dropdown Menu End */\r\n");
      out.write("\r\n");
      out.write("\t\t\t#container {\r\n");
      out.write("\t\t\t\tmargin: 0px auto;\r\n");
      out.write("\t\t\t\twidth: 570px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.clear {\r\n");
      out.write("\t\t\t\tclear: both;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.left {\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.right {\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\theader {\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\tpadding: 0px 0px 5px 0px;\r\n");
      out.write("\t\t\t\tmargin: -20px 0px 0px 0px;\r\n");
      out.write("\t\t\t\theight: 80px;\r\n");
      out.write("\t\t\t\twidth: 1200px;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tbackground-color: #ffcc99;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\theader hgroup {\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\theader #logo {\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<form method=\"post\" action=\"\" id=\"main-form\">\r\n");
      out.write("\t\t<div id=\"container\" style=\"height:130px; width:1200px; margin-top:-20px; background-color:#ffcc99; float:left\">\r\n");
      out.write("\t\t\t<div class=\"divRow1\">\r\n");
      out.write("\t\t\t\t<div class=\"divCell\" style=\"width:600px\">\r\n");
      out.write("\t\t\t\t\t<img id=\"logo\" src=\"../../Images/logo_car.jpg\" alt=\"Logo\" height=\"120\" width=\"250\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"divCell\" style=\"width:600px\">\r\n");
      out.write("\t\t\t\t\t<h1 align=\"right\">Buy On Mobile Inc.</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--<header style=\"height:100px; width:1200px; margin:-20px 0px 0px 32px; background-color:#ffcc99;\"> -->\r\n");
      out.write("\t\t<!--<header>\r\n");
      out.write("\t\t<hgroup  >\r\n");
      out.write("\t\t<h1 >ABC Solutions</h1>\r\n");
      out.write("\t\t</hgroup>\r\n");
      out.write("\t\t<img id=\"logo\" src=\"Images/logo_car.jpg\" alt=\"Logo\" height=\"80\" width=\"150\">\r\n");
      out.write("\t\t</header> -->\r\n");
      out.write("\t\t<div id=\"container\" style=\"height:25px; width:1200px; margin-top:-0px; background-color:#ffcc99; float:left\">\r\n");
      out.write("\t\t\t<!-- User Profile Menu Start -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<!--<a class=\"dropdown\" onclick=\"addContent('userDetails')\">User Profile</a>-->\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown\" href=\"/mobilizecarsweb/app/userDetails/getUser\" target=\"mainContentBody\">User Profile</a>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!--<li class=\"sublinks\"> <a href=\"#\">Link 1</a> <a href=\"#\">Link 2</a> </li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- User Profile Menu End -->\r\n");
      out.write("\t\t\t<!-- Use Preferences Menu Start -->\r\n");
      out.write("\t\t\t<!--  <ul>\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"dropdown\">User Preferences </a></li>\r\n");
      out.write("\t\t\t<li class=\"sublinks\"> <a href=\"#\">Link 1</a> <a href=\"#\">Link 2</a> </li>\r\n");
      out.write("\t\t\t</ul> -->\r\n");
      out.write("\t\t\t<!-- Use Preferences Menu End -->\r\n");
      out.write("\t\t\t<!-- Buyer Menu Start -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown\">Buy A Car</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"sublinks\">\r\n");
      out.write("                    <a href=\"/mobilizecarsweb/app/buyer/getPref\" target=\"mainContentBody\">Preferences</a>\r\n");
      out.write("                    <a href=\"/mobilizecarsweb/app/buyer/getCriteria\" target=\"mainContentBody\">Search Criteria</a>\r\n");
      out.write("                    <a href=\"/mobilizecarsweb/app/buyer/getResult\" target=\"mainContentBody\">Search Results</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- Buyer Menu End -->\r\n");
      out.write("\t\t\t<!-- Seller Menu Start -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown\">Sell A Car</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"sublinks\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/mobilizecarsweb/app/seller/addCar\" target=\"mainContentBody\">Add car</a>\r\n");
      out.write("                    <a href=\"/mobilizecarsweb/app/seller/makePay\" target=\"mainContentBody\">Make a payment</a>\r\n");
      out.write("                    <a href=\"/mobilizecarsweb/app/seller/carsList\" target=\"mainContentBody\">Car listings</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- Seller Menu End -->\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"/mobilizecarsweb/app/login/user\" class=\"dropdown\" target=\"_self\">Log Out</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("       <!-- <div name=\"dummy\"  id=\"dummy\" style=\"height:80px;  width:1200px;  float:left; background-color:#EBEBEB\"></div>\r\n");
      out.write("        <div name=\"mainContentBody\"  id=\"mainContentBody\" style=\"height:750px;  width:1200px;  float:left; background-color:#EBEBEB\"></div>-->\r\n");
      out.write("        <iframe name=\"mainContentBody\"  id=\"mainContentBody\" height=\"750px\"  width=\"1200px\"  frameborder=\"0\"></iframe>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
