/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-06-03 01:42:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sellerMakePay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=utf-8 />\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"../../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write("label {\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\twidth:140px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//$(function(){   $(\"#content\").load(\"mainPage_2.html\"); }); \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--<div name=\"content\" id=\"content\" style=\"height:130px; width:1200px; background-color:#ffcc99; float:left; margin:0px 0px 0px 0px\"></div>\r\n");
      out.write("<fieldset  style=\"margin-left:300px; height:300px; width:600px; float:left; border:solid thick\" >-->\r\n");
      out.write("<fieldset >\r\n");
      out.write("<legend>Seller Make Paymentss</legend>\r\n");
      out.write("<div >\r\n");
      out.write("  <label for=\"cardType\">Card Type:</label>\r\n");
      out.write("  <input type=\"text\" list=\"cardType_list\" name=\"cardType\" id=\"cardType\" required>\r\n");
      out.write("  <datalist id=\"cardType_list\">\r\n");
      out.write("    <option label=\"visa\" value=\"Visa\">\r\n");
      out.write("    <option label=\"master\" value=\"Master\">\r\n");
      out.write("    <option label=\"arericanExpress\" value=\"Arerican Express\">\r\n");
      out.write("    <option label=\"Discoveror\" value=\"Discoveror\"> \r\n");
      out.write("  </datalist>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"cNumber\">Card Number:</label>\r\n");
      out.write("  <input type=\"number\" name=\"cNumber\" id=\"cNumber\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"chName\">Card Holder Name:</label>\r\n");
      out.write("  <input type=\"text\" name=\"chName\" id=\"chName\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"model\">Model:</label>\r\n");
      out.write("  <input type=\"text\" name=\"model-local\" id=\"model\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"expDate\">Expiratuib Date:</label>\r\n");
      out.write("  <input type=\"date\" name=\"expDate\" id=\"expDate\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"cvvCOde\">CVV code:</label>\r\n");
      out.write("  <input type=\"number\" name=\"cvvCOde\" id=\"cvvCOde\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"amount\">Amount:</label>\r\n");
      out.write("  <input type=\"number\" name=\"amount\" id=\"amount\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"divTable\">\r\n");
      out.write("  <div class=\"divRow\">\r\n");
      out.write("    <div class=\"divCell\" align=\"right\">\r\n");
      out.write("      <input type=\"button\" name=\"save\" id=\"save\" value=\"Save\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"divCell\">\r\n");
      out.write("      <input type=\"button\" name=\"delete\" id=\"delete\" value=\"Delete\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
