/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-10-27 04:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsps;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=utf-8 />\r\n");
      out.write("<title></title>\r\n");
      out.write("<link href=\"../../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write("label {\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\twidth:110px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/*$(document).ready(function() {\r\n");
      out.write("\t$(\"#save\").click(function() {\r\n");
      out.write("\t\talert(\"submit-top\");\r\n");
      out.write("\t\tdocument.forms[\"userprof-form\"].action = \"/mobilizecarsweb/app/userDetails?pageType=save\";\r\n");
      out.write("\t\t//document.forms[\"userprof-form\"].target=window.opener.$('#mainContentBody');\r\n");
      out.write("\t\tdocument.forms[\"userprof-form\"].submit();\r\n");
      out.write("\t\t//$(\"#mainContentBody\").load(\"/mobilizecarsweb/app/userDetails?pageType=save\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("});*/\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"post\" id=\"userprof-form\" name=\"userprof-form\" action=\"/mobilizecarsweb/app/userDetails/saveUser\">\r\n");
      out.write("<!--<div name=\"content\" id=\"content\" style=\"height:130px; width:1200px; background-color:#ffcc99; float:left; margin:0px 0px 0px 0px\"></div>\r\n");
      out.write("<fieldset  style=\" margin-left:300px; height:350px; width:600px; float:left; border:solid #990000\" >-->\r\n");
      out.write("<fieldset >\r\n");
      out.write("<legend>User Profile</legend>\r\n");
      out.write("<div>\r\n");
      out.write("<font color='red' >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.resMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("  </font>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"firstName\">First Name:</label>\r\n");
      out.write("  <input type=\"text\" name=\"firstName\" id=\"firstName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("  <input type=\"text\" name=\"lastName\" id=\"lastName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"addressLine1\">Address Line1:</label>\r\n");
      out.write("  <input type=\"text\" name=\"addressLine1\" id=\"addressLine1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.addressLine1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"addressLine2\">Address Line2:</label>\r\n");
      out.write("  <input type=\"text\" name=\"addressLine2\" id=\"addressLine2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.addressLine2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"city\">City:</label>\r\n");
      out.write("  <input type=\"text\" name=\"city\" id=\"city\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<label for=\"state\">State:</label>\r\n");
      out.write("<input type=\"text\" name=\"state\" id=\"state\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"zip\">Zip Code:</label>\r\n");
      out.write("  <input type=\"text\" name=\"zip\" id=\"zip\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.zip}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<label for=\"country\">Country:</label>\r\n");
      out.write("<input type=\"text\" name=\"country\" id=\"country\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.country}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"homePhone\" >Home Phone:</label>\r\n");
      out.write("  <input type=\"tel\" name=\"homePhone\" id=\"homePhone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.homePhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"mobilePhone\" >Mobile Phone:</label>\r\n");
      out.write("  <input type=\"tel\" name=\"mobilePhone\" id=\"mobilePhone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.mobilePhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("  <label for=\"emailId\">Email:</label>\r\n");
      out.write("  <input type=\"email\" name=\"emailId\" id=\"emailId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userDetails.emailId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  required>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"divTable\">\r\n");
      out.write("  <div class=\"divRow\">\r\n");
      out.write("    <div class=\"divCell\" align=\"right\">\r\n");
      out.write("      <input type=\"submit\" name=\"save\" id=\"save\" value=\"Save\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"divCell\">\r\n");
      out.write("      <input type=\"button\" name=\"delete\" id=\"delete\" value=\"Delete\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
